---
title: "Veri Seti ve Ödev 1"
date: "Kasım, 2020"
output: word_document
---

Basamaklar:

A. Aşağıdaki veri setini inceleyiniz. Her öğrencinin kendi veri seti ayrıdır. Eğer ödev olarak başka bir arkadaşınızın veri setini kullanırsanız ödevlerinizden sıfır alırsınız. Veri setinin içinde 30 öğrenciye ait bilgiler vardır: Öğrencilerin numarası, cinsiyeti, yaşadıkları şehir, matematik puanları, fen bilgisi puanları ve bilime olan ilgileri. Bu veri setini diğer ödevleriniz için de kullanacaksınız. 

B. Ödev 1: Aşağıdaki soruları yanıtlayınız ve yanıtlarınızı Ödev 1 için verilen şablona uygun olarak excel formatında teslim ediniz.

- Cinsiyet verisi için frekans tablosu oluşturunuz (2 puan)
- Matematik puanları için mod (1p), medyan(1p) ve ortalama(1p) hesaplayınız 
- Matematik puanları için minimum(1p), maximum(1p), ranj(1p), varyans(3p) ve standart sapma (4p) hesaplayınız

Not: Birden fazla mod varsa en küçük olanı rapor ediniz.


\newpage


```{r results='asis', echo=FALSE, warning=FALSE, message=FALSE}
require(knitr)
# load("odevdata.RData")
# kaf=splitodev[[i]]
kable(kaf,row.names = F)

```




<!-- C. Ödev 2: Aşağıdaki soruları yanıtlayınız ve yanıtlarınızı Ödev 2 için verilen şablona uygun olarak excel formatında teslim ediniz. -->

<!-- - $H_0: \mu_{FenBil} = 5$ ve $H_1: \mu_{FenBil} \neq 5$ hipotezleri için t istatistiği nedir? (6p) -->
<!-- - Bu soru için alfa=.05 alınırsa t kritik mutlak değeri nedir?(2p) -->
<!-- - Bu soru için alfa=.01 alınırsa t kritik mutlak değeri nedir?(2p) -->
<!-- - Alfayı .05 alırsak, hangi hipotezi kabul etmeliyiz H0 mı H1 mi? H0 için 0, H1 için 1 yanıtı veriniz.(5p) -->

<!-- D. Ödev 3: Aşağıdaki soruları yanıtlayınız ve yanıtlarınızı Ödev 3 için verilen şablona uygun olarak excel formatında teslim ediniz. -->

<!-- - Matematik ve Fen bilgisi puanları arasındaki korelasyon nedir?(5p) -->
<!-- - Matematik ve Bilime ilgi puanları arasındaki korelasyon nedir?(5p) -->
<!-- - Fen bilgisi ve Bilime ilgi puanları arasındaki korelasyon nedir?(5p) -->


<!-- E. Ödev 4: Aşağıdaki soruları yanıtlayınız ve yanıtlarınızı Ödev 4 için verilen şablona uygun olarak excel formatında teslim ediniz. -->

<!-- - Bilime ilgi puanlarını kullanarak, $H_0:\mu_{Erkek}-\mu_{Kadin}=0$ ve $H_1:\mu_{Erkek}-\mu_{Kadin} \neq0$ hipotezleri için t istatistiği nedir? (6p) -->
<!-- - Bu soru için alfa=.05 alınırsa t kritik mutlak değeri nedir?(2p) -->
<!-- - Bu soru için alfa=.01 alınırsa t kritik mutlak değeri nedir?(2p) -->
<!-- - Alfayı .05 alırsak, hangi hipotezi kabul etmeliyiz H0 mı H1 mi? H0 için 0, H1 için 1 yanıtı veriniz.(5p) -->


<!-- F. Ödev 5: Aşağıdaki soruları yanıtlayınız ve yanıtlarınızı Ödev 5 için verilen şablona uygun olarak excel formatında teslim ediniz. -->

<!-- - Bilime ilgi puanlarını kullanarak,  -->
<!-- $H_0: \mu_{IST} = \mu_{ANK} = \mu_{IZM}$ -->

<!-- $H_1: \mu_{IST} \neq \mu_{ANK} \neq \mu_{IZM}$  -->


<!-- hipotezleri için F istatistiği nedir? (6p) -->
<!-- - Bu soru için alfa=.05 alınırsa F kritik mutlak değeri nedir?(2p) -->
<!-- - Bu soru için alfa=.10 alınırsa F kritik mutlak değeri nedir?(2p) -->
<!-- - Alfayı .05 alırsak, hangi hipotezi kabul etmeliyiz H0 mı H1 mi? H0 için 0, H1 için 1 yanıtı veriniz.(5p) -->


<!-- Not: ANOVA'da varyansların eşit olduğunu varsayınız. -->

<!-- G. Ödev 6: 3- Bilime olan ilgiyi Cinsiyet, Matematik ve Fen Bilgisi puanları ile tahmin ediniz.Aşağıdaki sorularda alfayı .05 alınız. Yanıtlarınızı Ödev 6 için verilen şablona uygun olarak excel formatında teslim ediniz. -->

<!-- -  Modelin geneli için boş ve alternatif hipotezinizi yazınız. Hesapladığınız istatistiği gösteren tabloyu ekleyiniz. Hangi hipotezi kabul ettiğinizi yazınız. (10puan) -->

<!-- - Matematik puanlarının Bilime olan ilgiyi tahmin edip edemediğini test ediniz. Boş ve alternatif hipotezinizi yazınız. Hesapladığınız istatistiği gösteren tabloyu ekleyiniz. Hangi hipotezi kabul ettiğinizi yazınız. (20puan) -->

<!-- - Fen Bilgisi puanlarının Bilime olan ilgiyi tahmin edip edemediğini test ediniz. Boş ve alternatif hipotezinizi yazınız. Hesapladığınız istatistiği gösteren tabloyu ekleyiniz. Hangi hipotezi kabul ettiğinizi yazınız. (20puan) -->

<!-- - Matematik puanı 7, Fen Bilgisi puanı 8 olan bir erkek öğrencinin bilime olan ilgisini tahmin ediniz. (10 puan) -->

<!-- - Bu regresyon modelinin sınırlılıkları nelerdir, en az 3 sınırlılık belirtiniz? Sonuçları bilimsel bir yayına çevirmeden önce nelere dikkat edilmelidir, en az 5 nokta belirtiniz? (40p) -->


